# Generated by Django 3.1.14 on 2022-06-06 14:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='account',
            field=models.CharField(default=datetime.datetime(2022, 6, 6, 14, 39, 27, 570205, tzinfo=utc), max_length=1000, verbose_name='ユーザー'),
            preserve_default=False,
        ),
    ]
